### ISSUE TITLE
Feature Request: Machine readable output

### ISSUE THREAD

**Issue by endzyme** [robscott/kube-capacity#10]
Outputting the same data in json would be awesome to leverage `jq` or other tools. Thoughts welcome on formatting or if this is a good feature request.

**Comment by robscott** [comment]
Great idea, @ivanfetch had suggested something similar as well for better accessibility.

**Comment by robscott** [comment]
Thanks for solving this with https://github.com/robscott/kube-capacity/pull/12! Hope to get a release out shortly.
