### ISSUE TITLE
Feature request : container view

### ISSUE THREAD

**Issue by ArnaudMsh** [robscott/kube-capacity#11]
Hello,

Would it be possible to get a container view?

Thanks for the work you've done here btw

**Comment by robscott** [comment]
Hey @ArnaudMsh that's an interesting idea. What would the output look like for that? Would we just add a container column after pods? There's already some work underway to support JSON output, this might fit in nicely after that bit of restructuring.

**Comment by ArnaudMsh** [comment]
Hello,

Yes I think one more column after pods is the way to go!
And for sure, --containers would implicitly include --pods informations

**Comment by robscott** [comment]
👍 That makes a lot of sense to me. I think this fit in nicely with some of the other restructuring happening.

**Comment by ArnaudMsh** [comment]
Thanks to you for this useful tool :)

**Comment by robscott** [comment]
Hey @ArnaudMsh, I just released a new version of kube-capacity (0.3.0) that includes this functionality, thanks for the idea!

**Comment by ArnaudMsh** [comment]
hey @robscott ! thanks it's working great and it's very useful (at least for me!!)
Have a good day :)
