### ISSUE TITLE
Option to specify kubernetes config file

### ISSUE THREAD

**Issue by akhan4u** [robscott/kube-capacity#18]
Hello there, 

It will be very convenient if you add option to specify the path to kubernetes config file. 

**Example:** ``` --kubeconfig="path-to-kubeconfig-file" ```

**Comment by robscott** [comment]
Hey @akhan4u, thanks for the idea! I'm open to a contribution for that additional flag. Despite not being documented, this does already support the `KUBECONFIG` environment variable that most other Kubernetes tools do. So as an example, something like this should work for you until a proper flag is added: `KUBECONFIG=~/.kube/config2 kube-capacity`

**Comment by srgvg** [comment]
FYI - KUBECONFIG can point to multiple config files, colon separated, but it seems to expect just a single config file. See #28

**Comment by bilalcaliskan** [comment]
@robscott i am a volunteer for that feature so can you assign it to me if everyone is OK with that?

**Comment by robscott** [comment]
Thanks for volunteering @bilalcaliskan! I've assigned this one to you if you still have time to work on it.

**Comment by bilalcaliskan** [comment]
@robscott hello again, i guess there is a misunderstanding with that issue. I see that that feature already implemented in the latest release.

[kubeconfig file path definition](https://github.com/robscott/kube-capacity/blob/master/pkg/cmd/root.go#L79)
[using that variable while creating clientset](https://github.com/robscott/kube-capacity/blob/master/pkg/capacity/capacity.go#L33)

**Comment by robscott** [comment]
🤦 Looks like I just missed adding it to the readme, thanks for catching that @bilalcaliskan!

**Comment by akhan4u** [comment]
> 

Yup, I confirm that the feature is already implemented. 
```
❯ kube-capacity version
kube-capacity version v0.7.0


❯ kube-capacity --help | grep kubecon
      --kubeconfig string         kubeconfig file to use for Kubernetes config
```

**Comment by akhan4u** [comment]
> @robscott @akhan4u hello again, i guess there is a misunderstanding with that issue. I see that feature already implemented earlier and exists in the latest release.
> 
> [kubeconfig file path definition](https://github.com/robscott/kube-capacity/blob/master/pkg/cmd/root.go#L79) [using that variable while creating clientset](https://github.com/robscott/kube-capacity/blob/master/pkg/capacity/capacity.go#L33)
> 
> Command line help page:
> 
> ```shell
> $ kube-capacity -h
>       ...
>       --kubeconfig string         kubeconfig file to use for Kubernetes config
>       ...
> ```


Yup, I confirm that the feature is already implemented. 
```
❯ kube-capacity version
kube-capacity version v0.7.0


❯ kube-capacity --help | grep kubecon
      --kubeconfig string         kubeconfig file to use for Kubernetes config
```

**Comment by bilalcaliskan** [comment]
@akhan4u can you close the issue then? thanks :)
