### ISSUE TITLE
consider using krew-plugin-release to bump krew-index

### ISSUE THREAD

**Issue by rajatjindal** [robscott/kube-capacity#20]
Hi Rob

I've created this github action [krew-plugin-release](https://github.com/rajatjindal/krew-plugin-release), that can be used to auto-bump the new version in krew-index when you publish a new release of your plugin.

Right now I am using this to publish the [modify-secret](https://github.com/rajatjindal/kubectl-modify-secret) krew plugin.

If this is something that interests you, I will be happy to open a PR for you.

Thanks
Rajat Jindal

**Comment by robscott** [comment]
Hey @rajatjindal, this looks really cool, would love a PR if you have time!

**Comment by rajatjindal** [comment]
awesome. thank you. I have started work on it, and will submit the PR as soon as I test it once.

**Comment by rajatjindal** [comment]
Between i should clarify that i changed the implementation from a github action (required a token of user) vs a webhook based implementation (use krew-release-bot account) to open the pr

This was changed based on discussions with the krew team
