### ISSUE TITLE
Percentages

### ISSUE THREAD

**Issue by plainlystated** [robscott/kube-capacity#31]
This is probably a dumb question, but I didn't see it in in the help or README.  What do the percentages mean for req/limit/usage?

**Comment by robscott** [comment]
@plainlystated That's a great question, I should clarify that better in the readme. The percentages indicate the percent of total allocatable resources the given container/pod/node is consuming. So as an example, on a Node with 4GB of allocatable memory, a pod with a resource limit of 1GB would have 25% associated with it.

The [relevant code](https://github.com/robscott/kube-capacity/blob/master/pkg/capacity/resources.go#L340) is pretty straightforward. In Kubernetes, allocatable is actually different than total capacity. The Kubernetes docs have a [good explanation of what allocatable resources mean](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#node-allocatable).

**Comment by plainlystated** [comment]
Great, that makes sense!  Thanks for explaining it.
