### ISSUE TITLE
Very cool utility is there an equivalent tool out there that doesn't require metrics-server but uses kube-state-metrics?

### ISSUE THREAD

**Issue by m0rganic** [robscott/kube-capacity#34]

**Comment by robscott** [comment]
Hey @m0rganic, that's a great question. I know the readme says that this relies on metrics-server but I'm not actually sure that it would break with kube-state-metrics, have you tried it? If so, do you get any error messages? When I initially wrote this I think the 2 most used options were metrics-server and heapster, and this didn't work with heapster. If it doesn't work with kube-state-metrics hopefully it's not too hard to add support here.

**Comment by robscott** [comment]
Got some time to look into this, and it appears that metrics-server and kube-state-metrics are actually exposing different sets of metrics. From what I can tell, kube-state-metrics does not expose the metrics we'd need (CPU and Memory utilization).

I found this description from a [Datadog blog post](https://www.datadoghq.com/blog/how-to-collect-and-graph-kubernetes-metrics/) quite useful:

>The kube-state-metrics service provides additional cluster information that Metrics Server does not. Metrics Server exposes statistics about the resource utilization of Kubernetes objects, whereas kube-state-metrics listens to the Kubernetes API and generates metrics about the state of Kubernetes objects: node status, node capacity (CPU and memory), number of desired/available/unavailable/updated replicas per Deployment, pod status (e.g., waiting, running, ready), and so on. The kube-state-metrics docs detail all the metrics that are available once kube-state-metrics is deployed.

I think that means we can close this. Feel free to reopen if I misunderstood anything.
