### ISSUE TITLE
number of pod per node

### ISSUE THREAD

**Issue by cloud-66** [robscott/kube-capacity#49]
Great plugin, very useful.  It just miss one thing.   Is it possible to add number of pods on node and show limit max pod number on node.
For example  column
```
 pods
99/110
```

**Comment by bilalcaliskan** [comment]
@robscott can you assign it to me please? I am a big fan of kube-capacity and I would like to contribute to that project.

**Comment by robscott** [comment]
@bilalcaliskan thanks for volunteering to work on this! I've assigned you the issue, will be great to have this feature added in.

**Comment by bilalcaliskan** [comment]
@robscott hello, i am currently working on that feature but i have a little question. Should we pass the argument like **--pod-count** to display pod count via argument which is false by default, or should we print the pod count all the time by default?
