### ISSUE TITLE
Calling bottle :unneeded is deprecated! There is no replacement.

### ISSUE THREAD

**Issue by PDVJAM** [robscott/kube-capacity#57]
```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the robscott/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/robscott/homebrew-tap/Formula/kube-capacity.rb:10
```

See that anytime I do a brew update or install now.

**Comment by robscott** [comment]
Thanks for the heads up, looks like we need to update to a goreleaser version that includes https://github.com/goreleaser/goreleaser/issues/2595. I'm a bit overloaded right now, so it might take a minute for me to get to it, but if anyone has time, PRs are very welcome.

**Comment by dewe** [comment]
As far as I can tell, the `.circleci/config.yml` downloads and uses the latest goreleaser. No fix needed, just a new patch release.
