### ISSUE TITLE
Upgrade k8s.io deps as v0.23.1

### ISSUE THREAD

**Issue by bilalcaliskan** [robscott/kube-capacity#63]
Since kube-capacity is using go 1.17 and client-go v0.23.4 is compatible with go 1.17, i think client-go dependency should be increased to take advantage of latest release. @robscott If you assign it to me, i can handle the upgrade process. Regards! Also i can upgrade all **direct** deps if you want.

**Comment by robscott** [comment]
Hey @bilalcaliskan upgrading deps would be great if you have time to do it, thanks for volunteering!

**Comment by bilalcaliskan** [comment]
@robscott sorry :) i am reopening issue now thanks!

**Comment by bilalcaliskan** [comment]
All direct deps are also updated
