### ISSUE TITLE
incorrect POD COUNT

### ISSUE THREAD

**Issue by cloud-66** [robscott/kube-capacity#69]
There was fixed #49  by #60 .  But it shows wrong number of pods, bigger than limit number. Because it shows all kind of pods : completed, Error  etc.
But it should show the same number as command kubectl describe node , "Non-terminated Pods"   field.  This field show if it possible to schedule pod on this node or not.

![image](https://user-images.githubusercontent.com/41143306/177380424-47c311a9-aee8-4ce9-b8ba-bbb9099aa8d2.png)

<img width="220" src="https://user-images.githubusercontent.com/41143306/177380568-3529149e-2521-4500-ae9d-88db4cdce5f4.png">

**Comment by robscott** [comment]
Fixed by #70, thanks @cloud-66!
