### ISSUE TITLE
Feature Request: Sorting

### ISSUE THREAD

**Issue by endzyme** [robscott/kube-capacity#9]
One ask here (which i'm happy help with) is a sort feature, Right now I'm with the `sort` command in linux and that works OK but it would be nice to sort things by default or with a flag. Bubbling signal of "oversubscription" to the top would be nice. In terms of the output with `--usage`, the parenthesis cause `sort` by column some issues since it wants to include the parenthesis in the evaluation of sort. As a minimal change, it would be helpful to not encapsulate the percents.

**Comment by robscott** [comment]
Another great idea, thanks! Would something like `--sort cpu.util` make sense? In that kind of syntax, valid options would be `cpu.requests`, `cpu.limits`, `cpu.util`, and similar with `mem` or `memory` prefixes? Maybe with an additional `--order` flag that could be `ascending` or `descending`?

**Comment by endzyme** [comment]
Yeah that looks awesome. Using `--sort-by` would be consistent with `kubectl`. I think we could skip ASC vs DESC for first iteration unless it's a simple addition.

**Comment by robscott** [comment]
@endzyme This feature was just released in 0.3.0, thanks for the help and ideas!
